apiVersion: v1
kind: Pod
metadata:
  name: quick-start
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  serviceAccountName: workload-identity-sa
  containers:
  - name: azcli
    image: mcr.microsoft.com/azure-cli
    command:
    - "/bin/bash"
    - "-c"
    - "sleep infinity"
  nodeSelector:
    kubernetes.io/os: linux